### ISSUE TITLE
Search not functioning

### ISSUE THREAD

**Issue by joeyv11** [lambda81/lambda-addons#49]
Lately I'm unable to search and find some of the shows I usually watch I.e ' dead files' or ' the amazing race canada'. The shows still show up on my favourites but are in searchable.

**Comment by joeyv11** [comment]
Are *not searchable

**Comment by joeyv11** [comment]
To be specific this is in the Genesis Add on notice it was after the recent update.

**Comment by s7eele** [comment]
I have used search in genesis 5 and did not have a problem, as soon as I am able I will test search for the shows you listed to see if I have same issue, ttys

**Comment by joeyv11** [comment]
Any updates on the shows we can't seem to find anymore ? Cheers :)

**Comment by s7eele** [comment]
hello again, sorry but got sidetracked

I just tried a search (tv shows->search) using the examples above (exactly) and both were successful on first try. I know he tweaked the search functions in latest release because there were some issues but I don't know the details. Are you sure your running v5.0.2? If so I would definitely try flushing the cache first but if your still having issues its probably going to require a log file. I'll check back later to see if it its resolved itself or to look for a log file.

**Comment by joeyv11** [comment]
All looks to be fixed. Thanks

**Comment by s7eele** [comment]
great to hear, lambda is awesome!
