### ISSUE TITLE
Genesis Trakt sysnc

### ISSUE THREAD

**Issue by zecompadre** [lambda81/lambda-addons#52]
Trakt sysnc

When syncing TV Show collection if the series is a remake, it synscs the wrong TV Show

examples:

The Returned
The Prisoner
The Newsroom
The Messengers
The Game
The Flash
Powers
Once Upon A Time
Scandal
Intelligence
Beauty and the Beast
Atlantis High
Aquarius
Empire
Castle
House of Cards

can someone help ?

tks

**Comment by zecompadre** [comment]
Checked now

TV Show House of Cards (2013) - sync ok all seasons, but images (artwork) and info (cast) from House of Cards (1990) :(

@lambda81 can u help ?

tks

**Comment by lambda81** [comment]
The sync is being made by the addon itself, the addon sends the ID of the show to Trakt or to Trakt addon.
Trakt has changed their tv show naming from TVDB to TMDB.
Use the TMDB scraper in order to import them to library, not the TVDB scraper.

**Comment by zecompadre** [comment]
then why will seek well the seasons and then the detail information will get wrong?

I just use genesis to sync :(

do not use any other scraper :(

**Comment by zecompadre** [comment]
@lambda81 can u help ?

tks

**Comment by s7eele** [comment]
hi @zecompadre when he suggests using the tmdb scraper he is talking about the scraper that kodi is using for your library, not anything within the genesis add-on itself, you should be able to find the items added to your library via genesis by going to 'videos->files->', highlight the entry for genesis tvshows (something like 'TVShows (Genesis)') then pull up the context menu and select 'Change Content', this should open a window which allows you to select the scraper that will be used when adding items to your kodi library through genesis, as he indicated above you are going to want to select and use the TMDB scraper for tvshows added to your library through genesis, the link below will take you to a wiki page that will hopefully help more that i have with the rambling above:

http://kodi.wiki/view/Adding_videos_to_the_library

good luck, definitely curious to hear how it goes for you so let us know, ttys

**Comment by zecompadre** [comment]
but why the 4.8.5 version work without changing anything ?

Genesis > Tools > Trakt > Import TV Collections ... what scraper use ?

**Comment by s7eele** [comment]
hi again @zecompadre im goin to oversimplify but to answer your question, it's because that version uses a different source for tv show data

with regard to changing the scraper your looking in the wrong place, you don't need to change anything within genesis, the import function creates a directory that it populates with the items your importing to your kodi library via genesis, kodi (not genesis) then scans this directory using the scraper you assign and adds the items to your kodi library, this is the scraper you need to change, the one kodi is using to scan the directory genesis created when you used the import function, it should be set to tmdb and that can be done using steps I outlined in last post, if I have explained properly my last post and the wiki I linked should make more sense now, hope it helps

**Comment by zecompadre** [comment]
Changing the scraper  "House of Cards (US)" (2013) is create as "House of Cards" directory, like this it will create problems with the same show of 1990, like this there's no problem if i don't run trakt.tv last script to update my view status of the shows episodes :(

can u add an option on tools to get view status from trakt.tv (then i don't need the trakt.tv script)? 

tks for the help

**Comment by zecompadre** [comment]
@lambda81 is that possible ?

tks

**Comment by zecompadre** [comment]
@lambda81 is that possible ?

tks
