### ISSUE TITLE
Latest Movies (Genesis 5.1.4) Not Working

### ISSUE THREAD

**Issue by Wahaib1981** [lambda81/lambda-addons#81]
I have Fresh installed Genesis on freshly installed kodi ( on my Vero TV & Raspberry Pi2) both the "Latest Movies" Folder is not accessible, when trying to access the it will show circling for 2 or 3 seconds and that is all, tried also reinstalling but simply won't work.

**Comment by ZeroXn** [comment]
predb.me, which is what genesis uses to get the latest movies list, seems to be blocking requests that use the same user-agent that this addon uses.

I fixed this by going to http://whatsmyuseragent.com/,
then replaced the user agent in the file <a href=https://github.com/lambda81/lambda-addons/blob/master/plugin.video.genesis/resources/lib/libraries/client.py#L54>resources/lib/libraries/client.py line 54</a>

this was kind of a pita to nail down because of so many try/except/pass blocks in the addon

**Comment by Wahaib1981** [comment]
Can you please Little elaborate in Details, i am kind of basic level not professional about Linux and command line.

**Comment by Wahaib1981** [comment]
Latest Movies Link Started working after following instructions.

**Comment by Roizlotolov** [comment]
Thanks This is Really usefull!!
